version: "2"

services:
  redis:
    image: quay.io/centos7/redis-5-centos7
    container_name: redis
    ports:
      - 6379:6379
    user: "1024"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: docker.io/rediscommander/redis-commander
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - 8081:8081
    depends_on:
      - redis
    user: "1024"

  fedmsg:
    container_name: fedmsg
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/packit/packit-service-fedmsg:dev
    depends_on:
      - redis
    command: listen-to-fedora-messaging
    environment:
      FEDORA_MESSAGING_CONF: /home/packit/.config/fedora.toml
    volumes:
      - ./packit_service_fedmsg:/usr/local/lib/python3.10/site-packages/packit_service_fedmsg:ro,Z
      # get it from secrets
      - ./fedora.toml:/home/packit/.config/fedora.toml:ro,Z
    user: "1024"
