---
- name: Install dependencies for fedora messaging consumer.
  hosts: all
  tasks:
    - name: Install all RPM/python packages needed to run fedora messaging consumer.
      ansible.builtin.dnf:
        name:
          - python3-celery
          - python3-redis # celery[redis]
          - redis # redis-cli
          - python3-click
          - git # setuptools-scm
          - fedora-messaging
          - python3-copr-messaging # json schemas
        state: present

    - name: Install pip deps
      ansible.builtin.pip:
        name:
          - sentry-sdk
        executable: pip3
