---
- name: This is a recipe for how to cook fedora messaging consumer
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
  tasks:
    - name: make packit home dir
      ansible.builtin.file:
        state: directory
        path: "{{ home_path }}"
        mode: 0776
    - name: Install packit-service-fedmsg
      ansible.builtin.pip:
        name: /src
        executable: pip3
    - name: Clean all the cache files (especially pip)
      ansible.builtin.file:
        state: absent
        path: ~/.cache/
